name: Emanuel Altenburger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e62a6'
    - '#000080'
    - '#000000'
    - '#0000ff'
    - '#003399'
  brandStrength: 0.375
  lightness: 0.6720511480234563
  saturation: 0.4700098189059645
  rhythmicContrast: 0.5196843876037747
purpose: []
